### ISSUE TITLE
Problem with connection - Connection could not be opened.

### ISSUE THREAD

**Issue by terciopadilha** [danikf/tik4net#31] opened 2018-07-04 18:00 UTC
Hello, how are you ?

I would first like to thank you for your beautiful work, you are helping me a lot with the management of the MKs.

I use the version made until Nov 12, 2017 and everything works fine, but when I upgrade to other versions the system stopped connecting, I noticed that changes were made to the OpenConnection async API (https://github.com/danikf/tik4net/commit) / 81f68f597cd4c33cb6ab858eca6ded46225cd57f # [diff-6fe9fe2e4206c910a881330d5648084f)

Do you have any idea what that might be? I use exactly as in the examples, I tried to run in debug mode however it returns a generic error.

Sorry for my language, but I'm using Google Translate

**Comment by danikf** [comment] 2018-07-04 18:18
Hi,
which version of .NET dou you use? I met this behavior on core2 (xamarin) application.
I have to examine it ...
D

**Comment by danikf** [comment] 2018-07-04 18:39
Hi,
the problem is connected with Open timeout, which is set to 5s (seams to be not enough for SSL connection).

try to use it this way (set ReceiveTimeout before Open) :
```
var connection = ConnectionFactory.CreateConnection(TikConnectionType.ApiSsl);  // Or Api
connection.ReceiveTimeout = 20 * 1000; //20s
connection.Open(host, user. pass);
```
Does it help?

D
https://github.com/danikf/tik4net/issues

**Comment by terciopadilha** [comment] 2018-07-04 18:45
I tried, however unsuccessfully, it got idle and returned the same error: tik4net.TikConnectionException: Connection could not be opened.

`
{
public static IEnumerable<DhcpServerLease> ConsultaLeases(int pIdDispositivo)
        {
            var connection = ConnectionFactory.CreateConnection(TikConnectionType.ApiSsl);

            connection.ReceiveTimeout = 20 * 1000;
            connection.Open("2ti.2ti.com.br", "admin", "password");
            connection.Encoding = Encoding.UTF7;

            var cmd = connection.CreateCommand("/ip/dhcp-server/lease/print");
            var leases = cmd.LoadList<DhcpServerLease>().ToList();

            return leases.OrderBy(d => IPAddress.Parse(d.Address), new IPAddressComparer());
        }
}`

**Comment by terciopadilha** [comment] 2018-07-04 18:48
I tried with or without SSL too

**Comment by danikf** [comment] 2018-07-05 14:49
Hopefully fixed in version 3.2.0.0 :-)
Please let me know if it helps in your case.

D

**Comment by terciopadilha** [comment] 2018-07-05 15:16
It worked !

Thank you very much and once again congratulations for the excellent work !!!

**Closed** 2018-07-05 15:48 UTC

**Comment by kadirSoyakaya** [comment] 2023-06-20 20:51
Can not read sentence from connection ??????
